// <auto-generated />
using System;
using BankMore.Account.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMore.Account.Infrastructure.Migrations
{
    [DbContext(typeof(BankMoreAccountContext))]
    [Migration("20260108183138_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankMore.Account.Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<Guid>("IdContaCorrente")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(37)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idcontacorrente");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"), 100000L);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("salt");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("senha");

                    b.HasKey("IdContaCorrente");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("contacorrente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ativo_Boolean", "ativo IN (0, 1)");
                        });
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Idempotencia", b =>
                {
                    b.Property<Guid>("ChaveIdempotencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chave_idempotencia");

                    b.Property<string>("Requisicao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("requisicao");

                    b.Property<string>("Resultado")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("resultado");

                    b.HasKey("ChaveIdempotencia");

                    b.ToTable("idempotencia", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Movimento", b =>
                {
                    b.Property<Guid>("IdMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idmovimento");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime")
                        .HasColumnName("datamovimento");

                    b.Property<Guid>("IdContaCorrente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idcontacorrente");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("tipomovimento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdContaCorrente");

                    b.ToTable("movimento", null, t =>
                        {
                            t.HasCheckConstraint("CK_TipoMovimento", "tipomovimento IN ('C', 'D')");
                        });
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.ContaCorrente", b =>
                {
                    b.HasOne("BankMore.Account.Domain.Entities.Usuario", "Usuario")
                        .WithOne("ContaCorrente")
                        .HasForeignKey("BankMore.Account.Domain.Entities.ContaCorrente", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Movimento", b =>
                {
                    b.HasOne("BankMore.Account.Domain.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany()
                        .HasForeignKey("IdContaCorrente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaCorrente");
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ContaCorrente");
                });
#pragma warning restore 612, 618
        }
    }
}
