// <auto-generated />
using System;
using BankMore.Transfer.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMore.Transfer.Infrastructure.Migrations
{
    [DbContext(typeof(BankMoreTransferContext))]
    partial class BankMoreTransferContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankMore.Transfer.Domain.Entities.Idempotencia", b =>
                {
                    b.Property<Guid>("ChaveIdempotencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chave_idempotencia");

                    b.Property<string>("Requisicao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("requisicao");

                    b.Property<string>("Resultado")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("resultado");

                    b.HasKey("ChaveIdempotencia");

                    b.ToTable("idempotencia", (string)null);
                });

            modelBuilder.Entity("BankMore.Transfer.Domain.Entities.Transferencia", b =>
                {
                    b.Property<Guid>("IdTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idtransferencia");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime")
                        .HasColumnName("datamovimento");

                    b.Property<Guid>("IdContaDestino")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idcontacorrente_destino");

                    b.Property<Guid>("IdContaOrigem")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idcontacorrente_origem");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdTransferencia");

                    b.ToTable("transferencia", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
